# Site settings
title: "Anabasis"
subtitle: "Na severní frontě klid"
email: afri@afri.cz
url: https://anabasis.larpy.cz
description: "Hra se inspiruje u airsoftových simulačních her a přenáší jejich principy do fantasy hry s kekelem. Asymetricky proti sobě stojí dvě strany: utábořená, těžce vyzbrojená jednotka se zázemím se snaží kontrolovat území. Proti Pluku stojí průzkumníci, kteří bez zázemí plní v terénu pozorovací, diverzní a jiné bojové úkoly."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#54cde6'

# Footer settings
footer: Anabasis Larp

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/anabasis.larp

# Build settings
markdown: kramdown
permalink: pretty
