# Site settings
title: Anabasis
email: afri@afri.cz
url: "https://anabasis-2017.larpy.cz"
description: "Anabasis je bojový larp. Anabasis je drsná a syrová hra. Anabasis se s hráči nemazlí a hodně od nich požaduje. Za to jim dá prožít opravdové přátelství ve zbrani, tvrdou bitku, vojáckou pitku a cestu do záhuby, na jejíž konec může dojít jen málokdo."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#54cde6'

# Footer settings
footer: Anabasis Larp

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/anabasis.larp

# Build settings
markdown: kramdown
permalink: pretty
